// Back Burner: pause goals without deleting them, then restore when ready.
(() => {
  const escSafe=v=>typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const activeGoals=()=> (state.goals||[]).filter(g=>!g.backBurner);
  const parkedGoals=()=> (state.goals||[]).filter(g=>!!g.backBurner);

  function persist(){ if(typeof save==='function') save(); else { try{localStorage.setItem('gcc-v1',JSON.stringify(state));}catch{} if(typeof render==='function')render(); } }
  function ensureStyles(){if(document.querySelector('#backBurnerStyles'))return;const s=document.createElement('style');s.id='backBurnerStyles';s.textContent=`
    .bb-section{margin-top:22px}.bb-head{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;flex-wrap:wrap;margin-bottom:12px}.bb-head h2{margin:4px 0}.bb-head p{margin:0;color:var(--muted);font-size:12px}.bb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.bb-card{padding:18px;opacity:.9}.bb-card h3{margin:8px 0 5px}.bb-meta{font-size:11px;color:var(--muted)}.bb-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.bb-empty{padding:20px;text-align:center;color:var(--muted)}.bb-send{white-space:nowrap}
  `;document.head.appendChild(s);}
  function park(id){const g=(state.goals||[]).find(x=>String(x.id)===String(id));if(!g)return;g.backBurner=true;g.backBurnerAt=new Date().toISOString();persist();if(typeof toast==='function')toast('Goal moved to Back Burner');setTimeout(enhance,0);}
  function restore(id){const g=(state.goals||[]).find(x=>String(x.id)===String(id));if(!g)return;g.backBurner=false;delete g.backBurnerAt;persist();if(typeof toast==='function')toast('Goal returned to active goals');setTimeout(enhance,0);}
  function addParkButtons(){document.querySelectorAll('.goal-card').forEach(card=>{const open=card.querySelector('.open-goal');if(!open)return;const id=open.dataset.id,g=(state.goals||[]).find(x=>String(x.id)===String(id));if(!g||g.backBurner||card.querySelector('.bb-send'))return;const b=document.createElement('button');b.type='button';b.className='secondary-btn bb-send';b.dataset.bbPark=id;b.textContent='Back Burner';const footer=card.querySelector('.goal-footer')||card;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();park(id)});footer.appendChild(b);});}
  function hideParkedCards(){document.querySelectorAll('.goal-card').forEach(card=>{const id=card.querySelector('.open-goal')?.dataset.id,g=(state.goals||[]).find(x=>String(x.id)===String(id));if(g?.backBurner)card.remove();});}
  function renderSection(){const view=document.querySelector('#goalsView');if(!view)return;view.querySelector('.bb-section')?.remove();const goals=parkedGoals(),section=document.createElement('section');section.className='bb-section';section.innerHTML=`<div class="bb-head"><div><div class="kicker">Paused, not forgotten</div><h2>Back Burner</h2><p>Goals you are not focusing on right now. Bring one back whenever you're ready.</p></div><span class="badge">${goals.length} parked</span></div>${goals.length?`<div class="bb-grid">${goals.map(g=>`<article class="card bb-card"><div class="badge">${escSafe(g.category||'Goal')}</div><h3>${escSafe(g.title||'Untitled goal')}</h3><div class="bb-meta">${g.targetDate?'Original target: '+escSafe(typeof fmt==='function'?fmt(g.targetDate):g.targetDate):'No target date'}</div><div class="bb-actions"><button type="button" class="primary-btn" data-bb-restore="${escSafe(g.id)}">Bring Back</button></div></article>`).join('')}</div>`:'<div class="card bb-empty">No goals are on the Back Burner.</div>'}`;view.appendChild(section);section.querySelectorAll('[data-bb-restore]').forEach(b=>b.addEventListener('click',()=>restore(b.dataset.bbRestore)));}
  function enhance(){ensureStyles();hideParkedCards();addParkButtons();renderSection();}
  const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){oldRender.apply(this,arguments);setTimeout(enhance,0);};}
  const oldProgress=window.overall;if(typeof oldProgress==='function'){window.overall=function(){const list=activeGoals();return list.length?Math.round(list.reduce((a,g)=>a+(typeof progress==='function'?progress(g):0),0)/list.length):0;};}
  document.addEventListener('click',e=>{if(e.target.closest('[data-view="goals"]'))setTimeout(enhance,0);});
  setTimeout(enhance,0);
})();