// Back Burner: dedicated section to pause and restore goals.
(() => {
  const view=document.querySelector('#backburnerView');
  if(!view)return;
  const escSafe=v=>typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const activeGoals=()=> (state.goals||[]).filter(g=>!g.backBurner);
  const parkedGoals=()=> (state.goals||[]).filter(g=>!!g.backBurner);
  function persist(){if(typeof save==='function')save();else{try{localStorage.setItem('gcc-v1',JSON.stringify(state));}catch{} if(typeof render==='function')render();}}
  function ensureStyles(){if(document.querySelector('#backBurnerStyles'))return;const s=document.createElement('style');s.id='backBurnerStyles';s.textContent=`.bb-shell{display:grid;gap:16px}.bb-hero{padding:22px}.bb-hero h2{margin:5px 0 6px}.bb-hero p{margin:0;color:var(--muted)}.bb-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.bb-card{padding:20px}.bb-list{display:grid;gap:9px;margin-top:12px}.bb-row{display:flex;align-items:center;gap:11px;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel2)}.bb-row input{width:19px;height:19px;accent-color:var(--accent)}.bb-main{min-width:0;flex:1}.bb-title{font-weight:850}.bb-meta{font-size:10px;color:var(--muted);margin-top:3px}.bb-empty{padding:18px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:12px}.bb-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:850px){.bb-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function park(id){const g=(state.goals||[]).find(x=>String(x.id)===String(id));if(!g)return;g.backBurner=true;g.backBurnerAt=new Date().toISOString();persist();renderBackBurner();if(typeof toast==='function')toast('Goal moved to Back Burner');}
  function restore(id){const g=(state.goals||[]).find(x=>String(x.id)===String(id));if(!g)return;g.backBurner=false;delete g.backBurnerAt;persist();renderBackBurner();if(typeof toast==='function')toast('Goal brought back');}
  function renderBackBurner(){ensureStyles();const active=activeGoals(),parked=parkedGoals();view.innerHTML=`<div class="bb-shell"><div class="card bb-hero"><div class="kicker">Pause without deleting</div><h2>Back Burner</h2><p>Check a goal to move it out of your active focus. Bring it back anytime when you're ready.</p></div><div class="bb-grid"><div class="card bb-card"><h3>Active goals</h3><div class="bb-list">${active.length?active.map(g=>`<label class="bb-row"><input type="checkbox" data-bb-park="${escSafe(g.id)}"><div class="bb-main"><div class="bb-title">${escSafe(g.title||'Untitled goal')}</div><div class="bb-meta">${escSafe(g.category||'Goal')} ${g.targetDate?'· '+escSafe(typeof fmt==='function'?fmt(g.targetDate):g.targetDate):''}</div></div><span class="badge">Send to Back Burner</span></label>`).join(''):'<div class="bb-empty">No active goals.</div>'}</div></div><div class="card bb-card"><h3>On the Back Burner</h3><div class="bb-list">${parked.length?parked.map(g=>`<div class="bb-row"><div class="bb-main"><div class="bb-title">${escSafe(g.title||'Untitled goal')}</div><div class="bb-meta">${escSafe(g.category||'Goal')} ${g.targetDate?'· '+escSafe(typeof fmt==='function'?fmt(g.targetDate):g.targetDate):''}</div></div><div class="bb-actions"><button type="button" class="primary-btn" data-bb-restore="${escSafe(g.id)}">Bring Back</button></div></div>`).join(''):'<div class="bb-empty">Nothing is parked right now.</div>'}</div></div></div></div>`;view.querySelectorAll('[data-bb-park]').forEach(cb=>cb.addEventListener('change',()=>{if(cb.checked)park(cb.dataset.bbPark);}));view.querySelectorAll('[data-bb-restore]').forEach(b=>b.addEventListener('click',()=>restore(b.dataset.bbRestore)));}
  function hideParkedGoalCards(){document.querySelectorAll('#goalsView .goal-card').forEach(card=>{const id=card.querySelector('.open-goal')?.dataset.id,g=(state.goals||[]).find(x=>String(x.id)===String(id));if(g?.backBurner)card.remove();});}
  document.addEventListener('click',e=>{if(e.target.closest('[data-view="backburner"]'))setTimeout(renderBackBurner,0);if(e.target.closest('[data-view="goals"]'))setTimeout(hideParkedGoalCards,0);});
  const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){oldRender.apply(this,arguments);setTimeout(()=>{hideParkedGoalCards();renderBackBurner();},0);};}
  renderBackBurner();hideParkedGoalCards();
})();