(() => {
  const target=()=>Number(state?.meta?.readingTarget)||6;
  function ensure(){state.readingList=Array.isArray(state.readingList)?state.readingList:[];state.meta=state.meta||{};}
  function ui(){
    ensure();
    let b=document.querySelector('[data-view="reading"]');
    if(!b){b=document.createElement('button');b.className='nav-item';b.dataset.view='reading';b.innerHTML='▤ <span>Reading</span>';document.querySelector('[data-view="habits"]')?.after(b)}
    b.onclick=()=>switchView('reading');
    if(!document.querySelector('#readingView')){const s=document.createElement('section');s.id='readingView';s.className='view';document.querySelector('#checkinView')?.before(s)}
    if(!document.querySelector('#readingStyle')){const s=document.createElement('style');s.id='readingStyle';s.textContent='.book-row{display:grid;grid-template-columns:1fr 150px 180px auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid rgba(255,255,255,.08)}.book-row:last-child{border-bottom:0}.book-title{font-weight:800}.book-author{font-size:13px;opacity:.7}.reading-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}@media(max-width:800px){.reading-grid,.book-row{grid-template-columns:1fr}}';document.head.appendChild(s)}
  }
  function syncGoal(){
    const key=state.meta?.readingGoalKey;if(!key)return;const g=(state.goals||[]).find(x=>x.seedKey===key);if(!g)return;
    g.subgoals=Array.isArray(g.subgoals)?g.subgoals:[];while(g.subgoals.length<target()){const n=g.subgoals.length+1;g.subgoals.push({id:id(),title:`Finish book ${n}`,targetDate:'',done:false})}
    const done=state.readingList.filter(x=>x.status==='Finished').length;g.subgoals.slice(0,target()).forEach((x,i)=>x.done=i<done);
  }
  function renderReading(){
    ui();const books=state.readingList,done=books.filter(x=>x.status==='Finished').length,now=books.filter(x=>x.status==='Reading').length,p=Math.min(100,Math.round(done/target()*100));
    const rows=books.map(x=>`<div class="book-row"><div><div class="book-title">${esc(x.title)}</div><div class="book-author">${esc(x.author||'')}</div></div><select class="r-status" data-id="${x.id}"><option ${x.status==='Want to read'?'selected':''}>Want to read</option><option ${x.status==='Reading'?'selected':''}>Reading</option><option ${x.status==='Finished'?'selected':''}>Finished</option></select><div style="display:flex;gap:6px"><input class="r-read" data-id="${x.id}" type="number" min="0" value="${Number(x.pagesRead)||0}" placeholder="Read"><input class="r-total" data-id="${x.id}" type="number" min="0" value="${Number(x.totalPages)||0}" placeholder="Total"></div><button class="icon-btn r-del" data-id="${x.id}">×</button></div>`).join('')||'<div class="empty">No books yet.</div>';
    const v=document.querySelector('#readingView');if(!v)return;v.innerHTML=`<div class="section-head" style="margin-top:0"><div><h2>Reading List</h2><p>Track books and reading progress.</p></div><button id="addBook" class="secondary-btn">+ Add book</button></div><div class="reading-grid"><div class="card"><div class="metric-label">Finished</div><div class="metric-value">${done}/${target()}</div></div><div class="card"><div class="metric-label">Reading now</div><div class="metric-value">${now}</div></div><div class="card"><div class="metric-label">Progress</div><div class="metric-value">${p}%</div><div class="progress"><span style="width:${p}%"></span></div></div></div><div class="card"><div class="list">${rows}</div></div>`;
    document.querySelector('#addBook')?.addEventListener('click',addBook);document.querySelectorAll('.r-status').forEach(e=>e.onchange=()=>chg(e.dataset.id,{status:e.value}));document.querySelectorAll('.r-read').forEach(e=>e.onchange=()=>chg(e.dataset.id,{pagesRead:+e.value||0}));document.querySelectorAll('.r-total').forEach(e=>e.onchange=()=>chg(e.dataset.id,{totalPages:+e.value||0}));document.querySelectorAll('.r-del').forEach(e=>e.onclick=()=>{state.readingList=state.readingList.filter(x=>x.id!==e.dataset.id);syncGoal();save()});
  }
  function chg(i,p){const b=state.readingList.find(x=>x.id===i);if(!b)return;Object.assign(b,p);if(b.totalPages&&b.pagesRead>=b.totalPages)b.status='Finished';syncGoal();save()}
  function addBook(){modal(`<h2>Add a book</h2><div class="field"><label>Title</label><input id="rbTitle"></div><div class="field"><label>Author</label><input id="rbAuthor"></div><div class="field"><label>Total pages</label><input id="rbPages" type="number" min="0"></div><div class="modal-actions"><button class="secondary-btn close-modal">Cancel</button><button id="rbSave" class="primary-btn">Add book</button></div>`);document.querySelector('#rbSave').onclick=()=>{const t=document.querySelector('#rbTitle').value.trim();if(!t)return;state.readingList.unshift({id:id(),title:t,author:document.querySelector('#rbAuthor').value.trim(),pagesRead:0,totalPages:+document.querySelector('#rbPages').value||0,status:'Want to read',notes:''});syncGoal();save();close();switchView('reading')}}
  ui();const s0=switchView;switchView=function(v){s0(v);if(v==='reading'){renderReading();document.querySelector('#viewTitle').textContent='Reading List';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='reading'))}};const r0=render;render=function(){r0();ui();renderReading()};ensure();syncGoal();saveLocal();render();
})();
