// Weekly Focus: a simple planning layer over existing goals and tasks.
(() => {
  const view=document.querySelector('#weeklyView');
  if(!view)return;
  const KEY='gcc-weekly-focus-v1';
  const escSafe=v=>typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  function week(){const n=new Date(),d=n.getDay(),mon=new Date(n);mon.setDate(n.getDate()-((d+6)%7));mon.setHours(0,0,0,0);const sun=new Date(mon);sun.setDate(mon.getDate()+6);const key=mon.toISOString().slice(0,10);return{mon,sun,key};}
  function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
  function tasksThisWeek(){const w=week(),a=dateKey(w.mon),b=dateKey(w.sun);return(state.tasks||[]).filter(t=>t.date&&t.date>=a&&t.date<=b);}
  function goalName(id){return(state.goals||[]).find(g=>String(g.id)===String(id))?.title||'General';}
  function ensureStyles(){if(document.querySelector('#weeklyFocusStyles'))return;const s=document.createElement('style');s.id='weeklyFocusStyles';s.textContent=`.wf-shell{display:grid;gap:16px}.wf-hero{padding:22px}.wf-hero h2{margin:5px 0 6px;font-size:27px}.wf-hero p{margin:0;color:var(--muted)}.wf-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.wf-card{padding:20px}.wf-card h3{margin:0 0 12px}.wf-field{margin-top:12px}.wf-field label{display:block;font-size:11px;font-weight:800;color:var(--muted);margin-bottom:6px}.wf-field input,.wf-field select,.wf-field textarea{width:100%}.wf-field textarea{min-height:80px;resize:vertical}.wf-progress{height:12px;border-radius:999px;background:var(--panel2);overflow:hidden;margin-top:10px}.wf-progress span{display:block;height:100%;background:var(--accent);border-radius:inherit}.wf-stat{font-size:34px;font-weight:900}.wf-sub{font-size:12px;color:var(--muted)}.wf-task{display:flex;gap:10px;align-items:flex-start;padding:10px 0;border-bottom:1px solid var(--line)}.wf-task:last-child{border-bottom:0}.wf-task input{margin-top:3px}.wf-priorities{display:grid;gap:10px}.wf-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px}@media(max-width:850px){.wf-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function renderWeekly(){ensureStyles();const w=week(),all=tasksThisWeek(),done=all.filter(t=>t.done).length,pct=all.length?Math.round(done/all.length*100):0,store=load(),data=store[w.key]||{},goals=(state.goals||[]).filter(g=>!g.archived);const opts=['<option value="">Choose a goal</option>',...goals.map(g=>`<option value="${escSafe(g.id)}">${escSafe(g.title)}</option>`)].join('');view.innerHTML=`<div class="wf-shell"><div class="card wf-hero"><div class="kicker">Weekly command</div><h2>Focus on what matters this week.</h2><p>${w.mon.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${w.sun.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</p></div><div class="wf-grid"><div class="card wf-card"><h3>This week's plan</h3><div class="wf-field"><label>Must Win</label><input id="wfMust" placeholder="The one result that makes this week a win" value="${escSafe(data.must||'')}"></div><div class="wf-priorities">${[1,2,3].map(n=>`<div class="wf-field"><label>Priority ${n}</label><select id="wfP${n}">${opts}</select></div>`).join('')}</div><div class="wf-field"><label>Weekly note</label><textarea id="wfNote" placeholder="What do you need to remember this week?">${escSafe(data.note||'')}</textarea></div><div class="wf-actions"><button id="wfSave" class="primary-btn">Save weekly focus</button></div></div><div class="card wf-card"><div class="kicker">Weekly progress</div><div class="wf-stat">${pct}%</div><div class="wf-sub">${done} of ${all.length} scheduled tasks completed</div><div class="wf-progress"><span style="width:${pct}%"></span></div><h3 style="margin-top:22px">This week's actions</h3><div>${all.length?all.map(t=>`<label class="wf-task"><input type="checkbox" data-wf-task="${escSafe(t.id)}" ${t.done?'checked':''}><span><strong>${escSafe(t.title||'Untitled')}</strong><div class="wf-sub">${escSafe(goalName(t.goalId))} · ${escSafe(t.date)}</div></span></label>`).join(''):'<div class="wf-sub">No tasks are scheduled this week yet.</div>'}</div></div></div></div>`;[1,2,3].forEach(n=>{const e=document.querySelector(`#wfP${n}`);if(e)e.value=data[`p${n}`]||'';});document.querySelector('#wfSave')?.addEventListener('click',()=>{const allData=load();allData[w.key]={must:document.querySelector('#wfMust')?.value.trim()||'',p1:document.querySelector('#wfP1')?.value||'',p2:document.querySelector('#wfP2')?.value||'',p3:document.querySelector('#wfP3')?.value||'',note:document.querySelector('#wfNote')?.value.trim()||''};save(allData);if(typeof toast==='function')toast('Weekly focus saved');});document.querySelectorAll('[data-wf-task]').forEach(cb=>cb.addEventListener('change',()=>{const t=(state.tasks||[]).find(x=>String(x.id)===String(cb.dataset.wfTask));if(t){t.done=cb.checked;if(typeof saveState==='function')saveState();else if(typeof save==='function')save();renderWeekly();}}));}
  window.renderWeeklyFocus=renderWeekly;
  const btn=document.querySelector('[data-view="weekly"]');if(btn)btn.addEventListener('click',()=>setTimeout(renderWeekly,0));
  renderWeekly();
})();