-- Goal Command Center: daily to-do email preferences and delivery log.

create table if not exists public.daily_email_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  email text not null,
  send_time time without time zone not null default '07:00',
  timezone text not null default 'America/New_York',
  include_habits boolean not null default false,
  send_empty boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_email_preferences enable row level security;

create policy "Users can read their own daily email preferences"
on public.daily_email_preferences for select
using (auth.uid() = user_id);

create policy "Users can insert their own daily email preferences"
on public.daily_email_preferences for insert
with check (auth.uid() = user_id);

create policy "Users can update their own daily email preferences"
on public.daily_email_preferences for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own daily email preferences"
on public.daily_email_preferences for delete
using (auth.uid() = user_id);

create table if not exists public.daily_email_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_date date not null,
  email text not null,
  item_count integer not null default 0,
  status text not null check (status in ('sent','failed','skipped')),
  provider_message_id text,
  error text,
  sent_at timestamptz not null default now(),
  unique (user_id, local_date)
);

alter table public.daily_email_log enable row level security;

create policy "Users can read their own daily email history"
on public.daily_email_log for select
using (auth.uid() = user_id);

create index if not exists daily_email_preferences_enabled_idx
on public.daily_email_preferences (enabled)
where enabled = true;

create index if not exists daily_email_log_user_date_idx
on public.daily_email_log (user_id, local_date desc);
